[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'pyyaml', 'pybind11', 'jinja2', 'ply']

[project]
name = 'hopium-libcamera'
version = '0.0.1'
description = 'libcamera python bindings'
readme = 'README.md'

[project.urls]
Source = "https://github.com/raspberrypi/pylibcamera"
"RPi libcamera Source" = "https://github.com/raspberrypi/libcamera"

[tool.meson-python.args]
setup = [
    '-Drevision=main',
    '-Drepository=https://github.com/raspberrypi/libcamera.git',
    '-Dversion=unknown'
]

[tool.flit.module]
name = "libcamera"
